# version: '3.8'

services:
  weekends-service:
    image: weekends
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT= 8181


