openapi: 3.0.3
info:
  title: VacationPayAPI
  description: |-
    Приложение "Калькулятор отпускных".
  contact:
    email: nirku0soft@yandex.ru
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
  
servers:
  - url: http://localhost:8181



paths:
  /calculacte:
    get:
      description: Получить сумму отпускных по кол-ву дней отпуска или по датам отпуска.
      operationId: getVacationPay
      parameters:
        - name: salary
          in: query
          required: true
          schema:
            type: number
            format: double

        - name: vacation_day_count
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: vacancy_start
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: vacancy_end
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Получить сумму отпускных
          content:
              application/json:
                schema:
                  type: number
                  format: double
            
                 
        
    



